package net.runelite.client.plugins.microbot.blackjack;

public enum BlackjackState
{
    STARTING,
    VALIDATING,
    RETURNING_TO_HOUSE,
    FINDING_TARGET,
    KNOCKING_OUT,
    PICKPOCKETING,
    WAITING_FOR_TARGET_CLEAR,
    HEALING,
    POSITIONING_COMBAT_RESET,
    ESCAPING_COMBAT,
    WAITING_FOR_COMBAT_CLEAR,
    EXITING_FOR_WINE,
    SECURING_WINE_EXIT,
    RESTOCKING_WINE,
    RETURNING_WITH_WINE,
    SECURING_WINE_ENTRY,
    HUMANIZER_MOUSE,
    HUMANIZER_MISCLICK,
    HUMANIZER_BREAK,
    STOPPED,
    ERROR
}
